[buildPlans.RamsevkaMono]
family = "Ramsevka Mono"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.RamsevkaMono.variants]
  inherits = "ss15"

    [buildPlans.RamsevkaMono.variants.design]
    zero = "oval-broken-slash"

[buildPlans.RamsevkaMono.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.RamsevkaMono.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.RamsevkaMono.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.RamsevkaMono.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.RamsevkaMono.widths.Normal]
shape = 600
menu = 5
css = "normal"
