[buildPlans.RamsevkaMonoPreview]
family = "Ramsevka Mono Preview"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.RamsevkaMonoPreview.variants]
  inherits = "ss15"

    [buildPlans.RamsevkaMonoPreview.variants.design]
    zero = "oval-broken-slash"

[buildPlans.RamsevkaMonoPreview.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.RamsevkaMonoPreview.widths.Normal]
shape = 600
menu = 5
css = "normal"
