[buildPlans.RamsevkaTerm]
family = "Ramsevka Term"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.RamsevkaTerm.variants]
  inherits = "ss15"

  [buildPlans.RamsevkaTerm.ligations]
  inherits = "dlig"

    [buildPlans.RamsevkaTerm.variants.design]
    one = "base-flat-top-serif"
    two = "straight-neck-serifed"
    three = "flat-top-serifed"
    four = "open-serifed"
    five = "upright-flat-serifed"
    six = "straight-bar"
    seven = "straight-serifed-crossbar"
    eight = "crossing"
    zero = "tall-slashed-cutout"


[buildPlans.RamsevkaTerm.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.RamsevkaTerm.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.RamsevkaTerm.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.RamsevkaTerm.weights.Bold]
shape = 700
menu = 700
css = 700

